/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvaliacoesRouteImport } from './routes/avaliacoes'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ServicosIndexRouteImport } from './routes/servicos.index'
import { Route as ServicosGeneroIndexRouteImport } from './routes/servicos.$genero.index'
import { Route as ServicosGeneroCategoriaRouteImport } from './routes/servicos.$genero.$categoria'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacoesRoute = AvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosIndexRoute = ServicosIndexRouteImport.update({
  id: '/servicos/',
  path: '/servicos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosGeneroIndexRoute = ServicosGeneroIndexRouteImport.update({
  id: '/servicos/$genero/',
  path: '/servicos/$genero/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosGeneroCategoriaRoute = ServicosGeneroCategoriaRouteImport.update({
  id: '/servicos/$genero/$categoria',
  path: '/servicos/$genero/$categoria',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/contato': typeof ContatoRoute
  '/galeria': typeof GaleriaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/studio': typeof StudioRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/servicos/': typeof ServicosIndexRoute
  '/servicos/$genero/$categoria': typeof ServicosGeneroCategoriaRoute
  '/servicos/$genero/': typeof ServicosGeneroIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/contato': typeof ContatoRoute
  '/galeria': typeof GaleriaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/studio': typeof StudioRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/servicos': typeof ServicosIndexRoute
  '/servicos/$genero/$categoria': typeof ServicosGeneroCategoriaRoute
  '/servicos/$genero': typeof ServicosGeneroIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/contato': typeof ContatoRoute
  '/galeria': typeof GaleriaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/studio': typeof StudioRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/servicos/': typeof ServicosIndexRoute
  '/servicos/$genero/$categoria': typeof ServicosGeneroCategoriaRoute
  '/servicos/$genero/': typeof ServicosGeneroIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avaliacoes'
    | '/contato'
    | '/galeria'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/studio'
    | '/blog/$slug'
    | '/blog/'
    | '/servicos/'
    | '/servicos/$genero/$categoria'
    | '/servicos/$genero/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avaliacoes'
    | '/contato'
    | '/galeria'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/studio'
    | '/blog/$slug'
    | '/blog'
    | '/servicos'
    | '/servicos/$genero/$categoria'
    | '/servicos/$genero'
  id:
    | '__root__'
    | '/'
    | '/avaliacoes'
    | '/contato'
    | '/galeria'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/studio'
    | '/blog/$slug'
    | '/blog/'
    | '/servicos/'
    | '/servicos/$genero/$categoria'
    | '/servicos/$genero/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvaliacoesRoute: typeof AvaliacoesRoute
  ContatoRoute: typeof ContatoRoute
  GaleriaRoute: typeof GaleriaRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  StudioRoute: typeof StudioRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServicosIndexRoute: typeof ServicosIndexRoute
  ServicosGeneroCategoriaRoute: typeof ServicosGeneroCategoriaRoute
  ServicosGeneroIndexRoute: typeof ServicosGeneroIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacoes': {
      id: '/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/': {
      id: '/servicos/'
      path: '/servicos'
      fullPath: '/servicos/'
      preLoaderRoute: typeof ServicosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$genero/': {
      id: '/servicos/$genero/'
      path: '/servicos/$genero'
      fullPath: '/servicos/$genero/'
      preLoaderRoute: typeof ServicosGeneroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$genero/$categoria': {
      id: '/servicos/$genero/$categoria'
      path: '/servicos/$genero/$categoria'
      fullPath: '/servicos/$genero/$categoria'
      preLoaderRoute: typeof ServicosGeneroCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvaliacoesRoute: AvaliacoesRoute,
  ContatoRoute: ContatoRoute,
  GaleriaRoute: GaleriaRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  StudioRoute: StudioRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServicosIndexRoute: ServicosIndexRoute,
  ServicosGeneroCategoriaRoute: ServicosGeneroCategoriaRoute,
  ServicosGeneroIndexRoute: ServicosGeneroIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
